[build]
command = "npm run build"
publish = "dist"

# ❗ Bảo toàn API proxy (không redirect về index.html)
[[redirects]]
from = "/api/*"
to = "http://13.239.139.152:8080/api/:splat"
status = 200
force = true

# ❗ Redirect các route frontend về index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
