[build]
command = "npm run build"
publish = "dist"

[[plugins]]
package = "@netlify/plugin-lighthouse"

# optional, deploy the lighthouse report to a path under your site
[plugins.inputs.audits]
output_path = "reports/lighthouse.html"

# ❗ Bảo toàn API proxy (không redirect về index.html)
[[redirects]]
from = "/api/*"
to = "http://3.27.168.183:8080/api/:splat"
status = 200
force = true

# ❗ Redirect các route frontend về index.html
[[redirects]]
from = "/*"
to = "/index.html"
status = 200
